---
- name: Update toutes les VMs
  hosts: all

  tasks:
    - name: Execution d'APT update
      ansible.builtin.apt:
        update_cache: True


- name: Installation d'Apache2 sur les VMs Web
  hosts: web

  tasks:
    - name: Installation de Apache2
      ansible.builtin.apt:
        name: apache2
        state: present