---
- name: Installation de Bind9 sur les machines DNS
  hosts: dns
  remote_user: root

  tasks:
  - name: Mis à jour des depots de paquets
    ansible.builtin.apt:
      update_cache: true


  - name: Installation de bind9
    ansible.builtin.package:
      name: bind9
      state: present


  - name: Enregistrement de la date
    ansible.builtin.shell: date +%s&
    register: timestamp
    run_once: true

  - name: Template jinja2
    ansible.builtin.template:
      src: templates/labzone.j2
      dest: /etc/bind/named.conf.local




- name: Utilisation du playbook du professeur
  hosts: all
  remote_user: root

  tasks:
    - import_tasks: "tasks/set_dns.yml"

        