---
- name: Installation de Bind9 sur les machines DNS
  hosts: dns
  remote_user: root

  tasks:
  - name: Mis à jour des depots de paquets
    ansible.builtin.apt:
      update_cache: true


  - name: Installation de bind9
    ansible.builtin.package:
      name: bind9
      state: present


  - name: Enregistrement de la date
    ansible.builtin.shell: date +%s&
    register: timestamp
    run_once: true

  - name: Création du template jinja2
    ansible.builtin.template:
      src: templates/labzone.j2
      dest: /etc/bind/db.lab.lan
      owner: bind
      group: bind
      mode: '0644'

  - name: Ajout de la déclaration de zone
    ansible.builtin.blockinfile:
      path: /etc/bind/named.conf.local
      state: present
      block: |
        zone "lab.lan" IN {
        type master;
        file "/etc/bind/db.lab.lan";
        };



  - name: Redémarrage de Bind
    ansible.builtin.service:
      name: named
      state: restarted




- name: Utilisation du playbook du professeur
  hosts: all
  remote_user: root

  tasks:
    - import_tasks: "tasks/set_dns.yml"


- name: Lancement du playbook loadbalancer
  hosts: lb
  remote_user: root
  vars: 
    liste_modules:
    - proxy_http
    - proxy_http2
    - proxy_balancer
    - lbmethod_byrequests
  tasks:
    - import_tasks: "tasks/loadbalancer.yml"

- name: Lancement du playbook pour le web
  hosts: web
  remote_user: root
  tasks:
    - import_tasks: "tasks/web.yml"

                       