---
- name: Installation de Bind9 sur les machines DNS
  hosts: dns
  remote_user: root

  tasks:
  - name: Mis à jour des depots de paquets
    ansible.builtin.apt:
      update_cache: true


  - name: Installation de bind9
    ansible.builtin.package:
      name: bind9
      state: present

- name: Configuration des paramètres DNS de toute les machines
  hosts: all
  remote_user: root

  tasks:
  - name: Utilisation du playbook du professeur
    import_tasks: "tasks/set_dns.yml"

        