---
- name: Mise à jour des depots
  ansible.builtin.apt:
    update_cache: true

- name: Installation de apache2
  ansible.builtin.package:
    name: apache2
    state: present

- name: Activation des modules
  community.general.apache2_module:
   name: "{{ item }}"
   state: present 
  loop: "{{ liste_modules }}"

- name: Création du template jinja2
  ansible.builtin.template:
    src: templates/lb-apache-conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
    owner: www-data
  register: template_a2

- name: Redémarrage d'Apache2
  ansible.builtin.service:
    name: apache2
    state: restarted
  when: template_a2 is changed
